### ISSUE TITLE
[Bug] OBS Crashes Erroneously on Exit

### ISSUE THREAD

**Issue by stevemaunsell** [MisutaaAsriel/obs-toolbar#4]
# Issue
Crash log is generated every time OBS is closed. The toolbar and OBS work fine. It's just crashing when OBS is closed. Log file [here](https://drive.google.com/file/d/1ZeP51KKNlyj7h7hFslFocyiRSt9uRuhV/view?usp=sharing).

# Steps to Reproduce
Simply closing OBS creates the crash log

# Expected Behavior
OBS not to crash

# Platforms
Win 10 22H2 19045

### OBS Version: #
29.0.0

# Notes

**Comment by MisutaaAsriel** [comment]
Yeah I need to look into this. It's an erroneous crash, but this didn't happen with with earlier versions of OBS 28.0 but at some point it did.

I have no idea what Tiny Tubular Task Thread is but that appears to be the offending component. My best guess is OBS is failing to release something the plug-in was using and "crashing".

I can poke around at it this week.

**Comment by MisutaaAsriel** [comment]
Talking in the official Discord, apparently this is a harmless crash, for the most part, and a common one with plugins. — Something about how OBS exits might be causing the Tiny Tubular Task Thread to free up memory that's already been freed by the plug-in.

I'll look into it more and see what's going wrong, but I can't make promises.

**Comment by MisutaaAsriel** [comment]
## Resolved in release [0.1.2](https://github.com/MisutaaAsriel/obs-toolbar/releases/tag/0.1.2)

Was related to how the scene name was gathered; memory needed to be released after applying the current scene text.
