### ISSUE TITLE
New installer can't handle Portable Installs of OBS

### ISSUE THREAD

**Issue by lcalder** [MisutaaAsriel/obs-toolbar#5]
# Issue

New installer just drops the files into C:\ProgramFiles\obs-studio\... so I need to locate them and put them into my custom installation folder and then go and delete the obs-studio folder tree in C:\ProgramFiles that was created by the installer.
It might be nice to have an msi installer for newbies and just the regular old zip for those of us that prefer that as many plugins seem to do.

**Comment by lcalder** [comment]
Thanks for a great plugin!

**Comment by MisutaaAsriel** [comment]
### Portable package added to [Release 0.1.2](https://github.com/MisutaaAsriel/obs-toolbar/releases/tag/0.1.2) for Windows systems.
