### ISSUE TITLE
[Request] Settings button & title change

### ISSUE THREAD

**Issue by stevemaunsell** [MisutaaAsriel/obs-toolbar#6]
# Request
1. Change the streaming title from "Status" to "Stream" so it would match and show "Stream: Inactive" and "Recording: Inactive"
2. Add a "Settings" button to match what is available in the standard 'Controls' dock

# Details
1. Change the streaming title from "Status" to "Stream" so it would match and show "Stream: Inactive" and "Recording: Inactive"
2. Add a "Settings" button to match what is available in the standard 'Controls' dock

**Comment by MisutaaAsriel** [comment]
Per #2 - The OBS Plugin API does not allow access to the settings nor virtual camera settings menus, to my knowledge. Will revisit if this changes or is changed.

I'll mull over changing the phrasing.
