### ISSUE TITLE
[Bug] dock name dissapears from the docks menu list

### ISSUE THREAD

**Issue by hjmeneses** [MisutaaAsriel/obs-toolbar#8]
# Issue
name of the dock no longer appearswith obs 30

# Steps to Reproduce
install plugin, loog at docks menu, there is an empty space for the dock window

# Expected Behavior
name should appear

# Platforms

- Windows 11-->

### OBS Version: #
30.0 beta 3

**Comment by MisutaaAsriel** [comment]
I have tested this on PC, and it wasn't present for me. I'll reopen this if it becomes reproducible.
